#############################################################################
# Makefile for building: AstChanMon
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Oct 5 14:23:15 2010
# Project:  AstChanMon.pro
# Template: app
# Command: /home/rudilee/Programs/qtsdk-2010.02/qt/bin/qmake -spec ../../../Programs/qtsdk-2010.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile AstChanMon.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../Programs/qtsdk-2010.02/qt/mkspecs/linux-g++ -I. -I../../../Programs/qtsdk-2010.02/qt/include/QtCore -I../../../Programs/qtsdk-2010.02/qt/include/QtNetwork -I../../../Programs/qtsdk-2010.02/qt/include/QtGui -I../../../Programs/qtsdk-2010.02/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/rudilee/Programs/qtsdk-2010.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/rudilee/Programs/qtsdk-2010.02/qt/lib -lQtGui -L/home/rudilee/Programs/qtsdk-2010.02/qt/lib -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/rudilee/Programs/qtsdk-2010.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		astchanmon.cpp \
		astmaniface.cpp \
		asthostform.cpp \
		flowlayout.cpp \
		astchanform.cpp moc_astchanmon.cpp \
		moc_astmaniface.cpp \
		moc_asthostform.cpp \
		moc_astchanform.cpp \
		qrc_icon.cpp
OBJECTS       = main.o \
		astchanmon.o \
		astmaniface.o \
		asthostform.o \
		flowlayout.o \
		astchanform.o \
		moc_astchanmon.o \
		moc_astmaniface.o \
		moc_asthostform.o \
		moc_astchanform.o \
		qrc_icon.o
DIST          = ../../../Programs/qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		AstChanMon.pro
QMAKE_TARGET  = AstChanMon
DESTDIR       = 
TARGET        = AstChanMon

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_astchanmon.h ui_asthostform.h ui_astchanform.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AstChanMon.pro  ../../../Programs/qtsdk-2010.02/qt/mkspecs/linux-g++/qmake.conf ../../../Programs/qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../../../Programs/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		/home/rudilee/Programs/qtsdk-2010.02/qt/lib/libQtGui.prl \
		/home/rudilee/Programs/qtsdk-2010.02/qt/lib/libQtCore.prl \
		/home/rudilee/Programs/qtsdk-2010.02/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec ../../../Programs/qtsdk-2010.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile AstChanMon.pro
../../../Programs/qtsdk-2010.02/qt/mkspecs/common/g++.conf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/common/unix.conf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/common/linux.conf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/qconfig.pri:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt_config.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/default_pre.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/debug.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/default_post.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/warn_on.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/qt.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/moc.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/resources.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/uic.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/yacc.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/lex.prf:
../../../Programs/qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf:
/home/rudilee/Programs/qtsdk-2010.02/qt/lib/libQtGui.prl:
/home/rudilee/Programs/qtsdk-2010.02/qt/lib/libQtCore.prl:
/home/rudilee/Programs/qtsdk-2010.02/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../Programs/qtsdk-2010.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile AstChanMon.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/AstChanMon1.0.0 || $(MKDIR) .tmp/AstChanMon1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AstChanMon1.0.0/ && $(COPY_FILE) --parents astchanmon.h astmaniface.h asthostform.h flowlayout.h astchanform.h .tmp/AstChanMon1.0.0/ && $(COPY_FILE) --parents icon/icon.qrc .tmp/AstChanMon1.0.0/ && $(COPY_FILE) --parents main.cpp astchanmon.cpp astmaniface.cpp asthostform.cpp flowlayout.cpp astchanform.cpp .tmp/AstChanMon1.0.0/ && $(COPY_FILE) --parents astchanmon.ui asthostform.ui astchanform.ui .tmp/AstChanMon1.0.0/ && (cd `dirname .tmp/AstChanMon1.0.0` && $(TAR) AstChanMon1.0.0.tar AstChanMon1.0.0 && $(COMPRESS) AstChanMon1.0.0.tar) && $(MOVE) `dirname .tmp/AstChanMon1.0.0`/AstChanMon1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AstChanMon1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_astchanmon.cpp moc_astmaniface.cpp moc_asthostform.cpp moc_astchanform.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_astchanmon.cpp moc_astmaniface.cpp moc_asthostform.cpp moc_astchanform.cpp
moc_astchanmon.cpp: asthostform.h \
		astmaniface.h \
		astchanform.h \
		flowlayout.h \
		astchanmon.h
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) astchanmon.h -o moc_astchanmon.cpp

moc_astmaniface.cpp: astmaniface.h
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) astmaniface.h -o moc_astmaniface.cpp

moc_asthostform.cpp: astmaniface.h \
		astchanform.h \
		flowlayout.h \
		asthostform.h
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) asthostform.h -o moc_asthostform.cpp

moc_astchanform.cpp: astchanform.h
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) astchanform.h -o moc_astchanform.cpp

compiler_rcc_make_all: qrc_icon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icon.cpp
qrc_icon.cpp: icon/icon.qrc \
		icon/arrow_down.png \
		icon/sound.png \
		icon/arrow_up.png \
		icon/accept.png \
		icon/telephone_go.png \
		icon/sound_none.png \
		icon/connect.png \
		icon/disconnect.png \
		icon/wrench_orange.png
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/rcc -name icon icon/icon.qrc -o qrc_icon.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_astchanmon.h ui_asthostform.h ui_astchanform.h
compiler_uic_clean:
	-$(DEL_FILE) ui_astchanmon.h ui_asthostform.h ui_astchanform.h
ui_astchanmon.h: astchanmon.ui
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/uic astchanmon.ui -o ui_astchanmon.h

ui_asthostform.h: asthostform.ui
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/uic asthostform.ui -o ui_asthostform.h

ui_astchanform.h: astchanform.ui
	/home/rudilee/Programs/qtsdk-2010.02/qt/bin/uic astchanform.ui -o ui_astchanform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp astchanmon.h \
		asthostform.h \
		astmaniface.h \
		astchanform.h \
		flowlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

astchanmon.o: astchanmon.cpp astchanmon.h \
		asthostform.h \
		astmaniface.h \
		astchanform.h \
		flowlayout.h \
		ui_astchanmon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o astchanmon.o astchanmon.cpp

astmaniface.o: astmaniface.cpp astmaniface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o astmaniface.o astmaniface.cpp

asthostform.o: asthostform.cpp asthostform.h \
		astmaniface.h \
		astchanform.h \
		flowlayout.h \
		ui_asthostform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o asthostform.o asthostform.cpp

flowlayout.o: flowlayout.cpp flowlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowlayout.o flowlayout.cpp

astchanform.o: astchanform.cpp astchanform.h \
		ui_astchanform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o astchanform.o astchanform.cpp

moc_astchanmon.o: moc_astchanmon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_astchanmon.o moc_astchanmon.cpp

moc_astmaniface.o: moc_astmaniface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_astmaniface.o moc_astmaniface.cpp

moc_asthostform.o: moc_asthostform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_asthostform.o moc_asthostform.cpp

moc_astchanform.o: moc_astchanform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_astchanform.o moc_astchanform.cpp

qrc_icon.o: qrc_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icon.o qrc_icon.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

